# Dockerfile.streamlit
FROM python:3.13-slim
WORKDIR /app
COPY requirements.txt .
RUN pip install -r requirements.txt
COPY streamlit/ ./streamlit/
CMD [ "streamlit", "run", "streamlit/app.py", "--server.port=8501", "--server.address=0.0.0.0"]