name: CI

on:
  pull_request:
  push:
    branches: [ main, feat/** ]

jobs:
  build-test:
    runs-on: ubuntu-20.04
    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.9.6"

      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt', 'pyproject.toml') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install deps (project + dev)
        run: |
            python -m pip install --upgrade pip
            pip install -r requirements.txt
            # dev tools
            pip install pytest ruff mlflow

      - name: Lint (ruff)
        run: |
            ruff --version
            # if you have ruff settings in pyproject.toml it will pick them up
            ruff check .

      - name: Run unit tests
        env:
          PYTHONPATH: ./src
        run: |
          pytest -q

      - name: MLflow smoke (local sqlite + local artifacts)
        env:
          PYTHONPATH: ./src
        run: |
          python - <<'PY'
          import mlflow, os, tempfile, json, time
          tracking_dir = tempfile.mkdtemp(prefix="mlruns_ci_")
          mlflow.set_tracking_uri("sqlite:///" + os.path.join(tracking_dir, "mlruns_ci.db"))
          mlflow.set_experiment("ci_smoke")
          with mlflow.start_run(run_name="smoke"):
              mlflow.log_param("ci", "true")
              mlflow.log_metric("ping", 1.0)
              mlflow.set_tag("component", "ci")
          # ensure run got written by listing experiments
          client = mlflow.tracking.MlflowClient()
          exps = client.search_experiments()
          assert any(e.name=="ci_smoke" for e in exps)
          PY

      - name: Metric gate (fail if pr_auc < threshold)
        run: |
          python scripts/ci_metric_gate.py --file eval_snapshot.json --metric pr_auc --threshold 0.90
